# NEMS Central Command Phonetics Dictionary
# Edit easily with nano: search = pronunciation

Nagios = Noggy-ose
SLA = S L A
NEMS = Nems
N.E.M.S. = Nems
CPU = C P U
WAN = Wan
MB/s = megabytes per second
KB/s = kilobytes per second
Mbps = megabits per second
Gbps = gigabits per second
ms = milliseconds
GB = gigabytes
MB = megabytes
SAAS = sass
API = A P I
