#!/bin/bash

package=nems-www

if [[ $EUID == 0 ]]; then
  echo "ERROR: This script must not be run as root" 2>&1
  exit 1
fi

dpkg-deb --build debpack ${package}.deb
mv ${package}.deb /srv/repos/apt/nems/
cd /srv/repos/apt/nems/
reprepro includedeb 1.6 ${package}.deb
rm ${package}.deb
