#!/bin/bash

ver=1.8

a2enmod ssl
a2dissite 000-default
a2ensite nems-dashboard
a2enmod rewrite

# For NEMS ULA SSO
a2enmod lua
a2enmod headers
a2enconf nems_sso

# Change Apache footer
a2enmod security2
a2enconf security
/bin/sed -i~ '/SecServerSignature/d' /etc/apache2/conf-available/security.conf
echo "SecServerSignature NEMS_Linux/$ver" >> /etc/apache2/conf-available/security.conf

# Increase upload size for background images
  if [[ -e /etc/php/*/phpdbg/php.ini ]]; then
    /bin/sed -i '/post_max_size =/c\; NEMS00001\npost_max_size = 20M' /etc/php/*/phpdbg/php.ini
    /bin/sed -i '/upload_max_filesize =/c\upload_max_filesize = 16M' /etc/php/*/phpdbg/php.ini
  fi
  if [[ -e /etc/php/*/phpdbg/php.ini ]]; then
    /bin/sed -i '/post_max_size =/c\; NEMS00001\npost_max_size = 20M' /etc/php/*/phpdbg/php.ini
    /bin/sed -i '/upload_max_filesize =/c\upload_max_filesize = 16M' /etc/php/*/phpdbg/php.ini
  fi

# Harden the folder against code being added by non-sudo user
# This prevents someone using sudoer access to compromize the server
chown -R root:root /var/www/html
chmod -R 755 /var/www/html

# Allow NEMS SST to save NagiosTV (NEMS Tactical Overview) config
if [[ -e /var/www/nagiostv/client-settings.json ]]; then
  chown www-data:www-data /var/www/nagiostv/client-settings.json
  chmod 664 /var/www/nagiostv/client-settings.json
  chmod 755 /var/www/nagiostv
fi

# When nems-info is called by the web interface (for NEMS Version info for example) it will try to create this folder but does not have write access.
# So pre-create it and give www-data access.
  if [[ ! -d /var/www/.nems_cache ]]; then
    mkdir /var/www/.nems_cache
    chown www-data:www-data /var/www/.nems_cache
    chmod 755 /var/www/.nems_cache
  fi

# Set permissions for sudoers file which allows www-data to run nems-userctl
  chown root:root /etc/sudoers.d/nems-userctl
  chmod 440 /etc/sudoers.d/nems-userctl

/bin/systemctl restart apache2
